[default]
extend-ignore-identifiers-re = [
    # Technical terms and acronyms
    "api",
    "APIs",
    "uuid",
    "UUIDs",
    "http",
    "https",
    "url",
    "urls",
    "json",
    "jwt",
    "cors",
    "env",
    "config",
    "configs",
    "auth",
    "oauth",
    "npm",
    "pnpm",
    "eslint",
    "typescript",
    "javascript",
    "fastapi",
    "uvicorn",
    "supabase",
    "postgres",
    "sql",
    "async",
    "await",
    "bool",
    "str",
    "int",
    "dict",
    "tuple",
    "enum",
    "kwargs",
    "args",
    "func",
    "param",
    "params",
    # Project specific
    "chunkr",
    "openai",
    "tiktoken",
    "psycopg",
    "dotenv",
    "pyproject",
    "uv",
    "ruff",
    "mypy"
]

[default.extend-words]
# Add custom word corrections here if needed
# "teh" = "the"

[files]
extend-exclude = [
    "*.lock",
    "*.min.js",
    "*.min.css",
    "node_modules/",
    ".git/",
    "dist/",
    "build/",
    "__pycache__/",
    "*.pyc"
] 