services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - supabase-db
    env_file:
      - ./apps/api/.env
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - app-network

  supabase-db:
    image: supabase/postgres:15.6.1.118
    ports:
      - 54321:54321
      - 54322:54322
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=off"
      - "-c"
      - "shared_preload_libraries=vector"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
