services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres-db
    env_file:
      - ./apps/api/.env
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - app-network

  postgres-db:
    image: supabase/postgres:15.6.1.118
    ports:
      - 54321:5432 # Map local 54321 to container's PostgreSQL port 5432
      - 54322:6543 # Map local 54322 to container's pooler port 6543
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "log_statement=none"
      - "-c"
      - "log_min_messages=error"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=off"
      - "-c"
      - "shared_preload_libraries=vector"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
