services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres-db
    environment:
      - HOST=postgres-db
      - PORT=5432
      - DBNAME=postgres
      - USER=postgres
      - PASSWORD=postgres
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          path: ./apps/api
          ignore:
            - __pycache__/
            - "*.pyc"
            - "*.pyo"
            - ".pytest_cache/"
            - ".coverage"
            - ".env"

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          path: ./apps/web
          ignore:
            - node_modules/
            - .next/
            - "*.log"
            - ".env*"

  postgres-db:
    image: pgvector/pgvector:pg17
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
