name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Web app checks
  web-checks:
    name: Web App Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/web
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.1
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Run ESLint
        run: pnpm lint
      
      - name: Type check
        run: pnpm build --dry-run || echo "No dry-run available, running full build"
      
      - name: Build check
        run: pnpm build

  # Python API checks  
  api-checks:
    name: API Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      
      - name: Install dependencies
        run: uv sync
      
      - name: Run Ruff linter
        run: uv run ruff check .
      
      - name: Run Ruff formatter
        run: uv run ruff format --check .
      
      - name: Type check with mypy
        run: uv run mypy . --ignore-missing-imports || echo "mypy not configured yet"

  # Spell checking
  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run spell check
        uses: crate-ci/typos@v1.26.8
        with:
          files: |
            ./README.md
            ./apps/web/src
            ./apps/api/src
            ./.github
          config: ./.typos.toml
